[project]
name = "amm-deploy"
authors = ["BlockChain Developer"]
description = "An advanced automatic market maker (AMM) deployment smart contract"
telemetry = false
requirements = []
[contracts.amm-core]
path = "contracts/amm-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
